{{- define "k8s-git-server.usersConfig" -}}
{{- range $user := .Values.git.users }}
  '{{ $user.name }}': |
    {{- range $repo := $user.repos }}
    {{ $repo.path }}
    {{- end }}
{{- end }}
{{- end -}}

{{- define "k8s-git-server.flagsConfig" -}}
{{- range $uix, $user := .Values.git.users }}
{{- range $rix, $repo := $user.repos }}
{{- with $repo.source }}
{{- with .tarFlags }}
  '{{ $uix }}-{{ $rix }}': |
    {{- range . }}
    {{- . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-git-server.fullname" . }}-users
  labels:
    {{ include "k8s-git-server.labels" . | nindent 4 }}
data:
{{- include "k8s-git-server.usersConfig" . | nindent 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-git-server.fullname" . }}-flags
  labels:
    {{ include "k8s-git-server.labels" . | nindent 4 }}
data:
{{- include "k8s-git-server.flagsConfig" . | nindent 0 }}
---
