{{- if and .Values.persistence.enabled (not .Values.persistence.existingPersistentVolumeClaim.name) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-git-server.pvcName" . }}
  labels:
    {{- include "k8s-git-server.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes:
  {{- .Values.persistence.accessModes | toYaml | nindent 2 }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
